# Generated by Django 5.0 on 2023-12-19 10:44

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Plant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, default="", max_length=200)),
                (
                    "location",
                    models.CharField(
                        choices=[
                            ("LRBT", "living room black table & around"),
                            ("LRH", "living room hanging"),
                            ("LRWT", "living room white tables"),
                            ("BS", "bookshelves"),
                            ("OWS", "outside window sill"),
                            ("IWS", "inside window sill - living room"),
                            ("B1", "bedroom 1"),
                            ("B2", "bedroom 2"),
                            ("SC", "special care"),
                        ],
                        default="LRWT",
                        max_length=9,
                    ),
                ),
                ("frequency", models.IntegerField(blank=True, default=1, null=True)),
                ("instructions", models.TextField(blank=True, default="")),
                ("start", models.DateTimeField(blank=True, null=True)),
                ("end", models.DateTimeField(blank=True, null=True)),
                ("added", models.DateTimeField(auto_now_add=True)),
                ("changed", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
