# Generated by Django 5.0 on 2024-01-29 10:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="plant",
            name="photo",
            field=models.CharField(default="", max_length=200),
        ),
    ]
