# Generated by Django 5.0 on 2024-01-29 16:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="plant",
            name="photourl",
        ),
    ]
