# Generated by Django 5.0 on 2024-01-19 08:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="plant",
            options={"ordering": ["name"]},
        ),
        migrations.AddField(
            model_name="plant",
            name="volume",
            field=models.CharField(
                choices=[
                    ("100_ml", "100 ml"),
                    ("200_ml", "200 ml"),
                    ("300_ml", "300 ml"),
                    ("400_ml", "400 ml"),
                    ("500_ml", "500 ml"),
                ],
                default="100_ml",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="plant",
            name="name",
            field=models.CharField(default="", max_length=200),
        ),
    ]
