# Generated by Django 5.0 on 2023-12-19 10:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0002_alter_plant_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plant",
            name="location",
            field=models.CharField(
                choices=[
                    ("living_room_black", "living room black table & around"),
                    ("living_room_hanging", "living room hanging"),
                    ("living_room_white", "living room white tables"),
                    ("bookshelves", "bookshelves"),
                    ("window_outside", "outside window sill"),
                    ("window_inside", "inside window sill - living room"),
                    ("bedroom1", "bedroom 1"),
                    ("bedroom2", "bedroom 2"),
                    ("special_care", "special care"),
                ],
                default="living_room_white",
                max_length=100,
            ),
        ),
    ]
