# Generated by Django 5.0 on 2024-02-12 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0002_remove_plant_photourl"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plant",
            name="photo",
            field=models.ImageField(upload_to=""),
        ),
    ]
