# Generated by Django 5.0 on 2024-01-29 10:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0002_plant_photo"),
    ]

    operations = [
        migrations.RenameField(
            model_name="plant",
            old_name="photo",
            new_name="photourl",
        ),
    ]
