# Generated by Django 5.0 on 2024-01-25 10:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0002_alter_plant_options_plant_volume_alter_plant_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="plant",
            name="status",
            field=models.BooleanField(null=True),
        ),
    ]
