# Generated by Django 5.0 on 2024-02-05 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0003_rename_photo_plant_photourl"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plant",
            name="location",
            field=models.CharField(
                choices=[
                    ("living room black table & around", "living_room_black"),
                    ("living room hanging", "living_room_hanging"),
                    ("living room white tables", "living_room_white"),
                    ("bookshelves", "bookshelves"),
                    ("outside window sill", "window_outside"),
                    ("inside window sill - living room", "window_inside"),
                    ("bedroom 1", "bedroom1"),
                    ("bedroom 2", "bedroom2"),
                    ("special care", "special_care"),
                ],
                default="living_room_white",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="plant",
            name="status",
            field=models.CharField(
                choices=[("watered", "watered"), ("needs watering", "needs watering")],
                default="needs_watering",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="plant",
            name="volume",
            field=models.CharField(
                choices=[
                    ("100 ml", "100 ml"),
                    ("200 ml", "200 ml"),
                    ("300 ml", "300 ml"),
                    ("400 ml", "400 ml"),
                    ("500 ml", "500 ml"),
                ],
                default="100_ml",
                max_length=100,
            ),
        ),
    ]
