# Generated by Django 5.0 on 2024-01-25 12:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0003_plant_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plant",
            name="status",
            field=models.CharField(
                choices=[
                    ("100_ml", "100 ml"),
                    ("200_ml", "200 ml"),
                    ("300_ml", "300 ml"),
                    ("400_ml", "400 ml"),
                    ("500_ml", "500 ml"),
                ],
                default="100_ml",
                max_length=100,
            ),
        ),
    ]
