# Generated by Django 5.0 on 2024-01-25 12:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0004_alter_plant_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plant",
            name="status",
            field=models.CharField(
                choices=[("watered", "watered"), ("needs_watering", "needs watering")],
                default="needs_watering",
                max_length=100,
            ),
        ),
    ]
