# Generated by Django 5.0 on 2024-02-12 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0004_alter_plant_location_alter_plant_status_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="plant",
            name="photo",
        ),
    ]
