# Generated by Django 5.0 on 2024-02-12 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0006_plant_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plant",
            name="location",
            field=models.CharField(
                choices=[
                    (
                        "living room black table & around",
                        "living room black table & around",
                    ),
                    ("living room hanging", "living room hanging"),
                    ("living room white tables", "living room white tables"),
                    ("bookshelves", "bookshelves"),
                    ("outside window sill", "outside window sill"),
                    (
                        "inside window sill - living room",
                        "inside window sill - living room",
                    ),
                    ("bedroom 1", "bedroom 1"),
                    ("bedroom 2", "bedroom 2"),
                    ("special care", "special care"),
                ],
                default="living room white tables",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="plant",
            name="status",
            field=models.CharField(
                choices=[("watered", "watered"), ("needs watering", "needs watering")],
                default="needs watering",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="plant",
            name="volume",
            field=models.CharField(
                choices=[
                    ("100 ml", "100 ml"),
                    ("200 ml", "200 ml"),
                    ("300 ml", "300 ml"),
                    ("400 ml", "400 ml"),
                    ("500 ml", "500 ml"),
                ],
                default="100 ml",
                max_length=100,
            ),
        ),
    ]
