# Generated by Django 5.0 on 2024-05-15 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0008_alter_plant_location_alter_plant_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plant",
            name="photo",
            field=models.ImageField(default="", upload_to="uploads"),
        ),
    ]
