# Generated by Django 5.0 on 2024-05-31 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0009_alter_plant_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plant",
            name="status",
            field=models.BooleanField(default=False),
        ),
    ]
